name: PHP Matrix Tests

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3', '8.4']
        
    name: PHP ${{ matrix.php-version }} Tests
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: bcmath, gmp, sqlite3, mbstring, curl, dom, xml
          coverage: none

      - name: Show versions
        run: |
          php -v
          php -m
          composer -V || true

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies (composer install)
        run: |
          composer --version || curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          # Use --ignore-platform-reqs due to legacy dependency constraints
          composer install --no-interaction --prefer-dist --no-progress --ignore-platform-reqs

      - name: Run tests
        run: |
          mkdir -p build/test-results
          echo "Running modern PHPUnit 10 test suite on PHP ${{ matrix.php-version }}"
          
          # Run our modern test suite with PHPUnit 10
          ./vendor/bin/phpunit --configuration phpunit.xml \
            --log-junit build/test-results/junit-php${{ matrix.php-version }}.xml
          
          echo "✅ Tests completed successfully on PHP ${{ matrix.php-version }}"

      - name: Upload test results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-junit-php${{ matrix.php-version }}
          path: build/test-results/junit-php${{ matrix.php-version }}.xml